import shutil

import ffmpeg

AMBIENT_RATE = 44100
AMBIENT_EXPR = (
    "0.08*(0.6+0.4*sin(2*PI*0.08*t))"
    "*(sin(2*PI*110*t)+sin(2*PI*165*t)+sin(2*PI*220*t))/3"
)


def _ambient_pad(duration: float):
    """Soft three-tone pad with a slow LFO swell, generated by ffmpeg aevalsrc."""
    src = f"aevalsrc=exprs={AMBIENT_EXPR}|{AMBIENT_EXPR}:s={AMBIENT_RATE}:d={duration:.3f}"
    return ffmpeg.input(src, f="lavfi").audio


def mix_narration_with_music(
    narration_path: str,
    out_path: str,
    music_path: str | None = None,
    auto_ambient: bool = False,
    music_volume: float = 0.18,
) -> str:
    if not music_path and not auto_ambient:
        shutil.copyfile(narration_path, out_path)
        return out_path

    duration = float(ffmpeg.probe(narration_path)["format"]["duration"])
    fade = min(1.5, duration / 4)

    if music_path:
        music = ffmpeg.input(music_path, stream_loop=-1).audio.filter("atrim", duration=duration)
    else:
        music = _ambient_pad(duration)
    music = (
        music.filter("asetpts", "PTS-STARTPTS")
        .filter("volume", music_volume)
        .filter("afade", type="in", start_time=0, duration=fade)
        .filter("afade", type="out", start_time=max(0.0, duration - fade), duration=fade)
    )

    narration = ffmpeg.input(narration_path).audio
    mixed = ffmpeg.filter([music, narration], "amix", inputs=2, duration="longest", normalize=0)
    (
        ffmpeg.output(mixed, out_path, t=duration, acodec="libmp3lame", audio_bitrate="192k", ar=AMBIENT_RATE)
        .overwrite_output()
        .run(quiet=True)
    )
    return out_path
